### PR TITLE
Create ru_ru.json

### PR DESCRIPTION
**Pull request by mpustovoi**
Created ru_ru.json

### CODE REVIEW

**Comment by ThePotatoArchivist** [comment]
Thanks for the translation! Can I move it to datagen?

**Comment by mpustovoi** [comment]
To be honest, I don't know what it is. Therefore, I think it's up to you to decide.

**Comment by ThePotatoArchivist** [comment]
Updated, also because I forgot to update my `main` branch there are two untranslated strings. If you want to add those edit [`src/main/java/archives/tater/unbalancedmusket/datagen/RussianLangGenerator.java`](https://github.com/mpustovoi/TotallyBalancedMusket/blob/main/src/main/java/archives/tater/unbalancedmusket/datagen/RussianLangGenerator.java)

**Comment by mpustovoi** [comment]
Done.

**Pull request merged**
